---
- name: install apache2 or httpd
  hosts: all
  become: true
  tasks:
    - name: install apache2
      apt:
        name: apache2
        state: latest
      when: ansible_os_family == 'Debian'
    - name: start apache2
      service:
        name: apache2
        state: started
        enabled: true
      when: ansible_os_family == 'Debian'
    - name: restart apache2
      service:
        name: apache2
        state: restarted
      when: ansible_os_family == 'Debian'

    - name: install httpd
      dnf:
        name: httpd
        state: latest
      when: ansible_os_family == 'Redhat'
    - name: start httpd
      service:
        name: httpd
        state: started
        enabled: true
      when: ansible_os_family == 'Redhat'
    - name: restart httpd
      service:
        name: httpd
        state: restarted
      when: ansible_os_family == 'Redhat'

    - name: copy our custom page
      ansible.builtin.copy:
        src: /home/ubuntu/Ansible/website/Altschool-First_semester_assignment_one
        dest: /var/www/html/
        owner: root
        group: root
        mode: '0644'

    - name: reload apache2 or httpd
      ansible.builtin.service:
        name: "{{ 'apache2' if ansible_os_family == 'Debian' else 'httpd' }}"
        state: reloaded
